[package]
name = "cutting_corners"
version = "0.1.0"
authors = ["eraiser <krotttendorfer@hotmail.de>"]
edition = "2018"

[dependencies]
cgmath = "0.16.1"
glium = "0.23.0"
glutin = "0.19.0"
image = "0.20.1"
genmesh = "0.6.2"
gilrs = "0.6.2"
obj-rs = "0.4.20"
time = "0.1.42"